### ISSUE TITLE
No way to add link label?

### ISSUE THREAD

**Issue by joshmouch** [zHaytam/Blazor.DatabaseDesigner#1]
I'm not able to add the "0...*" label to the relationship like what is displayed in your screenshot.  Am I missing something?

**Comment by zHaytam** [comment]
Hi,
Please check the following line: https://github.com/Blazor-Diagrams/Blazor.DatabaseDesigner/blob/e9ce8e49231b9279e68c4f6d2a00653db712c5af/DatabaseDesigner.Wasm/Pages/Index.razor.cs#L63
